# Generated by Django 4.2.4 on 2025-02-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraisscolarite',
            name='est_paye_tranche1',
            field=models.BooleanField(default=False),
        ),
    ]
