# Generated by Django 4.2.4 on 2025-01-21 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eleve', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fraisscolarite',
            old_name='montant_paye',
            new_name='solde',
        ),
        migrations.RemoveField(
            model_name='fraisscolarite',
            name='date_paiement_complet',
        ),
        migrations.RemoveField(
            model_name='fraisscolarite',
            name='statut',
        ),
        migrations.AddField(
            model_name='fraisscolarite',
            name='total_paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fraisscolarite',
            name='tranche1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fraisscolarite',
            name='tranche2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fraisscolarite',
            name='annee_scolaire',
            field=models.CharField(max_length=9),
        ),
        migrations.CreateModel(
            name='Recu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_recu', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField()),
                ('frais_scolarite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleve.fraisscolarite')),
            ],
        ),
    ]
