# Generated by Django 4.2.4 on 2024-12-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
