# Generated by Django 4.2.4 on 2025-02-08 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annee_scolaire', '0001_initial'),
        ('eleve', '0002_fraisscolarite_est_paye_tranche1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraisscolarite',
            name='annee_scolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annee_scolaire.anneescolaire'),
        ),
    ]
