# Generated by Django 4.2.4 on 2025-01-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleve', '0002_rename_montant_paye_fraisscolarite_solde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraisscolarite',
            name='est_paye_tranche2',
            field=models.BooleanField(default=False),
        ),
    ]
