# Generated by Django 4.2.4 on 2025-02-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleve', '0003_alter_fraisscolarite_annee_scolaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraisscolarite',
            name='annee_scolaire',
            field=models.CharField(max_length=9),
        ),
    ]
