# Generated by Django 4.2.4 on 2025-01-29 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enseignant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_depense', models.DateField(default=django.utils.timezone.now)),
                ('categorie', models.CharField(choices=[('Matériel', 'Matériel'), ('Électricité', 'Électricité'), ('Eau', 'Eau'), ('Maintenance', 'Maintenance'), ('Autre', 'Autre')], default='Autre', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='enseignant/img/'),
        ),
    ]
