# Generated by Django 4.2.4 on 2024-12-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='Sexe',
            field=models.CharField(choices=[('H', 'Masculin'), ('F', 'Feminin')], max_length=10),
        ),
    ]
