# Generated by Django 4.2.4 on 2024-12-25 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matiere', '0001_initial'),
        ('eleve', '0001_initial'),
        ('annee_scolaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_comp', models.FloatField()),
                ('note_cours', models.FloatField()),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annee_scolaire.anneescolaire')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleve.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matiere.matiere')),
            ],
        ),
    ]
