# Generated by Django 4.2.4 on 2025-02-15 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groupe_classe', '0001_initial'),
        ('eleve', '0005_alter_fraisscolarite_annee_scolaire'),
        ('annee_scolaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinTrimestriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.PositiveIntegerField()),
                ('moyenne_trimestrielle', models.FloatField(blank=True, null=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annee_scolaire.anneescolaire')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleve.eleve')),
                ('groupe_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupe_classe.groupeclasse')),
            ],
        ),
        migrations.CreateModel(
            name='BulletinAnnuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField(blank=True, null=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annee_scolaire.anneescolaire')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleve.eleve')),
            ],
        ),
    ]
