# Generated by Django 4.2.4 on 2025-02-16 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletintrimestriel',
            name='groupe_classe',
        ),
        migrations.RemoveField(
            model_name='bulletintrimestriel',
            name='moyenne_trimestrielle',
        ),
    ]
