# Generated by Django 4.2.4 on 2025-01-05 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bulletin', '0001_initial'),
        ('groupe_classe', '0001_initial'),
        ('annee_scolaire', '0001_initial'),
        ('eleve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletintrimestriel',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleve.eleve'),
        ),
        migrations.AddField(
            model_name='bulletintrimestriel',
            name='groupe_classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groupe_classe.groupeclasse'),
        ),
        migrations.AddField(
            model_name='bulletinannuel',
            name='annee_scolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annee_scolaire.anneescolaire'),
        ),
        migrations.AddField(
            model_name='bulletinannuel',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleve.eleve'),
        ),
    ]
