# Generated by Django 4.2.4 on 2025-01-05 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletintrimestriel',
            name='groupe_classe',
        ),
    ]
